FROM debian:stretch

RUN apt-get update --fix-missing
RUN apt-get install -y kcachegrind

#sudo docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $PWD/Web/var:/var/profiler  kcachegrind bash
